export default function FilterableMenuTableBody() {
  return (
    <tbody>
      <tr>
        <td>메가반점</td>
        <td>중식</td>
        <td>
          <ul>
            <li>짜장면(8,000원)</li>
            <li>짬뽕(8,000원)</li>
            <li>차돌짬뽕(9,000원)</li>
            <li>탕수육(14,000원)</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td>메리김밥</td>
        <td>한식</td>
        <td>
          <ul>
            <li>김밥(3,500원)</li>
            <li>참치김밥(4,500원)</li>
            <li>제육김밥(5,000원)</li>
            <li>훈제오리김밥(5,500원)</li>
            <li>컵라면(2,000원)</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td>데브부엌</td>
        <td>한식</td>
        <td>
          <ul>
            <li>제육덮밥(10,000원)</li>
            <li>닭떡국(9,000원)</li>
            <li>닭개장(11,000원)</li>
            <li>돈까스(1,000원)</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td>로드스시</td>
        <td>일식</td>
        <td>
          <ul>
            <li>모듬초밥(14,000원)</li>
            <li>특선초밥(17,900원)</li>
            <li>스페셜초밥(21,000원)</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td>혹등고래카레</td>
        <td>일식</td>
        <td>
          <ul>
            <li>기본카레(9,000원)</li>
            <li>가라아게카레(14,000원)</li>
            <li>소시지카레(13,000원)</li>
            <li>돈까스카레(14,000원)</li>
            <li>닭가슴살카레(13,000원)</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td>메가김치찌개</td>
        <td>한식</td>
        <td>
          <ul>
            <li>김치찌개1인(8,000원)</li>
            <li>된장찌개(8,000원)</li>
            <li>계란말이(6,000원)</li>
          </ul>
        </td>
      </tr>
    </tbody>
  );
}
